services:
  postgres-test:
    image: postgres:16
    container_name: stranger-video-postgres-test
    restart: "no"

    environment:
      POSTGRES_DB: stranger_video_call_test
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: change_this_local_password

    ports:
      - "5433:5432"